name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'README.md'

permissions:
  contents: read

jobs:
  publish-pages:
    uses: Knuckles-Team/pipelines/.github/workflows/pages_pipeline.yml@73915f29ae672003a0bed287f85e19390d55f4d0
    with:
      content_source: docs
      shared_theme_enabled: true
    permissions:
      contents: read
      pages: write
      id-token: write
