name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'README.md'

permissions:
  contents: read

jobs:
  publish-pages:
    uses: Knuckles-Team/pipelines/.github/workflows/pages_pipeline.yml@fb5c0c941ea5a69f1c76e7c4819302e79cfe5e8a
    with:
      content_source: docs
      shared_theme_enabled: true
    permissions:
      contents: read
      pages: write
      id-token: write
