name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'README.md'

permissions:
  contents: read

jobs:
  publish-pages:
    uses: Knuckles-Team/pipelines/.github/workflows/pages_pipeline.yml@e841cfe67d3e13ddf52aee32a4580f9c7cf9ec80
    with:
      content_source: docs
      shared_theme_enabled: true
    permissions:
      contents: read
      pages: write
      id-token: write
