name: Build|Upload|Release Python Package

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  publish:
    uses: Knuckles-Team/pipelines/.github/workflows/python_pipeline.yml@main
    permissions:
      contents: write
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
