name: Cross-Platform Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    uses: Knuckles-Team/pipelines/.github/workflows/desktop_release_pipeline.yml@dc60f5ca0cfd00bf2e66f912a33d6d0f8ee62874 # v2.0.1
    permissions:
      contents: write
